### ISSUE TITLE
Clash of identical visible names of chat

### ISSUE THREAD

**Issue by lit34** [aahnik/telegram-chat-forward#1]
Hello and thank you for your work. I've been using your script and is working really good. But i encountered a problem. Telegram allows identical names for chats visible names, only their user-names are unique. So i wanted to copy files from 3 public channels to my private channel, but these public channels names are the same. So the script only copied files from one of this channels. 

How does your script differentiate between channels that have identical visible names? There must be a way to separate them and uniquely identify them. Is there a possibility to use user-names of channels instead of visible names?

**Comment by aahnik** [comment]
Hi @lit34 I am aware of this possible issue, but I have used visible name instead of user name because private channels and groups don't have user name.

I understand your use case and will modify the code to support both username and visible name.

In future, to use username in `to` and `from` fields in the config, you have to use the `@` prefix.


For example, 

`@example` will mean that `example` is the username, but `example` will mean that `example` is visible name.

( This will be a future feature, I will hopefully do it soon, and inform you, once the new version is out )

Thanks a lot for pointing out.

**Comment by aahnik** [comment]
Trying to implement this, I found out a terrible silly mistake that I had made. See ce798df5985eb1f760ad520ec14576f2f5b669f1

Your feature has not yet been implemented.

**Comment by aahnik** [comment]
## the `from` and `to` fields can be either chat id or visible name

**NEW FEATURE**: :tada:  You may use the chat_id instead of the visible name. To get the chat id of a particular chat/group/channel run `get_chat_id.py` and then enter the user-name/phone/link of the chat.

An example is here:


![get chat id](https://github.com/aahnik/telegram-chat-forward/blob/main/images/get_chat_id.gif?raw=true)

After getting the chat id you can use this in the `config.ini` file

```
[my config]
from = 90984098590
to = My Channel
offset = 0
; the from and to fields can be either chat id or visible name
```

**Comment by aahnik** [comment]
@lit34 Please test the new feature, and give your feedback.

**Comment by lit34** [comment]
Thank you for your quick response. I tried again with the new chat ids but I receive an error
"ValueError: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x000002700F7EFEE0>"

After I research a little on internet I found a solution here
https://www.xspdf.com/resolution/53139794.html
"Every channel id is a 13 characters negative integer. So the id for this channel is -1001035716040 and not 1035716040 as printed."

So I modified chat ids by putting -100 in front of them. It worked! Now the only problem I encounter is the flood messages that forces the script to take 5 min pause. If there are many files to be copied the pause is getting bigger, 60 minutes. I guess there are some limits that Telegram enforces. Are these known? Maybe an option to copy at a slower pace will not trigger these bans? A nice enhancement could be the option to copy only some types of posts and exclude others (video, audio, photos, links, excluding posts that contain certain words etc).

Thank you again for your effort, your script is the only one that worked for me, and I tried quite a few of them.

**Comment by aahnik** [comment]
hi @lit34 you can easily get chat ids by running `get_chat_id.py`. And it works, directly, I have tested.

You don't need to add `-100` in front.

I think you made some kind of error.

I highly recommend using `visible names`. If visible names collide, then take the link of the channel/group and generate the chat id.

FloodWait is caused by Telegram, because it puts some limitations on the no. of messages you can send in a given time.

Sending messages slowly is a bad idea, in my opinion.  That will take more total time, for a person who has fewer messages.

Waiting when we encounter FloodLimits is better.

**Comment by aahnik** [comment]
For general help and discussion please chat with me on Telegram.

Click this button [![telegram-chat](https://img.shields.io/badge/chat-@aahnikdaw-blue?logo=telegram)](https://telegram.me/aahnikdaw)

**Comment by aahnik** [comment]
> A nice enhancement could be the option to copy only some types of posts and exclude others (video, audio, photos, links, excluding posts that contain certain words etc).

Thats a good idea, but I am currently busy with other work. You are most welcome to contribute the new feature.

**Comment by aahnik** [comment]
@lit34 From now on, you can directly use username in `from` and `to`

**Comment by lit34** [comment]
I deleted all and setup a fresh configuration. Now it works! Keep up the good work!
